# 测试用例
person:
  name : 何加玮
  age : 25


# 配置端口号和路径
server :
  port : 8081
  context-path : /hjw
  tomcat :
    uri-encoding : UTF-8

#spring 配置
spring:
  # 配置数据库信息
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hjw?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: root
 #     password: 123456
  # 集成hibernate
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: UTC
  http:
      encoding:
        force: true
        charset: UTF-8
        enabled : true
  thymeleaf:
    prefix: classpath:/templates/WEB-INF/views/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  activiti:
  #  false：false为默认值，设置为该值后，Activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配时，将在启动时抛出异常。
  #  true：设置为该值后，Activiti会对数据库中所有的表进行更新，如果表不存在，则Activiti会自动创建。
  #  create-drop：Activiti启动时，会执行数据库表的创建操作，在Activiti关闭时，执行数据库表的删除操作。
  #  drop-create：Activiti启动时，执行数据库表的删除操作在Activiti关闭时，会执行数据库表的创建操作。
  # 设置为该值后，Activiti会对数据库中所有的表进行更新，如果表不存在，则Activiti会自动创建。和jpa类似,true每次启动检查,false不检查
        database-schema-update: true
        check-process-definitions: true
        process-definition-location-prefix: classpath:/processes/
    #    processes-definition-location-suffixes:
    #      - **.bpmn
    #      - **.bpmn20.xmlqingjia.bpmn20.xml
  #保存历史数据级别设置为full最高级别，便于历史数据的追溯
  #  none：不保存任何的历史数据，因此，在流程执行过程中，这是最高效的。
  #  activity：级别高于none，保存流程实例与流程行为，其他数据不保存。
  #  audit：除activity级别会保存的数据外，还会保存全部的流程任务及其属性。audit为history的默认值。
  #  full：保存历史数据的最高级别，除了会保存audit级别的数据外，还会保存其他全部流程相关的细节数据，包括一些流程参数等。
        history-level: full


# 集成mybatis
mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.huz.hjw.bean

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# 日志
logging:
  file: /own/bootsy/log/mylog.log
  level:
    org:
      springframework:
        web: debug
    com:
      huz:
        hjw:
          dao : debug